master:
  image: redis:3
  ports:
      - "6379:6379"
slave-1:
  image: redis:3
  command: redis-server --slaveof redis-master 6379
  links:
    - master:redis-master
  ports:
      - "6380:6379"
slave-2:
  image: redis:3
  command: redis-server --slaveof redis-master 6379
  links:
    - master:redis-master
  ports:
      - "6381:6379"
sentinel-1:
  build: sentinel
  environment:
    - SENTINEL_DOWN_AFTER=5000
    - SENTINEL_FAILOVER=5000    
  links:
    - master:redis-master
    - slave-1
    - slave-2
  ports:
      - "16379:26379"
sentinel-2:
  build: sentinel
  environment:
    - SENTINEL_DOWN_AFTER=5000
    - SENTINEL_FAILOVER=5000    
  links:
    - master:redis-master
    - slave-1
    - slave-2
  ports:
      - "16380:26379"
sentinel-3:
  build: sentinel
  environment:
    - SENTINEL_DOWN_AFTER=5000
    - SENTINEL_FAILOVER=5000    
  links:
    - master:redis-master
    - slave-1
    - slave-2
  ports:
      - "16381:26379"
